version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: fridgewiseai-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: fridgewiseai
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - fridgewiseai-network

  recognize-api:
    image: mnahkies/recognize-anything-api:latest
    container_name: fridgewiseai-recognize-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - fridgewiseai-network

  # Alternative CPU-only version if GPU not available
  recognize-api-cpu:
    image: mnahkies/recognize-anything-api:latest
    container_name: fridgewiseai-recognize-api-cpu
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=""
    profiles:
      - cpu
    networks:
      - fridgewiseai-network

volumes:
  mongodb_data:

networks:
  fridgewiseai-network:
    driver: bridge