services:
  recognize-api:
    image: mnahkies/recognize-anything-api:latest
    container_name: fridgewiseai-recognize-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - fridgewiseai-network

  # Alternative CPU-only version if GPU not available
  recognize-api-cpu:
    image: mnahkies/recognize-anything-api:latest
    container_name: fridgewiseai-recognize-api-cpu
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=""
    profiles:
      - cpu
    networks:
      - fridgewiseai-network

volumes:
  placeholder:

networks:
  fridgewiseai-network:
    driver: bridge