services:
  mongodb:
    image: mongo:7.0
    container_name: fridgewiseai-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: fridgewiseai
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - fridgewiseai-network

  redis:
    image: redis:7.2-alpine
    container_name: fridgewiseai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - fridgewiseai-network

  recognize-api:
    image: mnahkies/recognize-anything-api:latest
    container_name: fridgewiseai-recognize-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=""
    networks:
      - fridgewiseai-network

volumes:
  mongodb_data:
  redis_data:

networks:
  fridgewiseai-network:
    driver: bridge