version: '3.8'

services:
  fridgewiseai-landing:
    build:
      context: .
      dockerfile: Dockerfile
    image: fridgewiseai-landing:latest
    container_name: fridgewiseai-landing
    ports:
      - "3001:3000"  # Host:Container - mappa porta 3001 dell'host alla 3000 del container
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy (opzionale)
  nginx:
    image: nginx:alpine
    container_name: fridgewiseai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - fridgewiseai-landing
    restart: unless-stopped